<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "factura".
 *
 * @property integer $id
 * @property string $fecha_factura
 * @property string $nroFactura
 * @property string $informada
 * @property string $fecha_informada
 * @property string $monto
 * @property string $cae
 * @property string $ptoVta
 * @property integer $id_tiket
 * @property string $errores
 *
 * @property \app\models\Tiket $tiket
 * @property string $aliasModel
 */
abstract class Factura extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'factura';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha_factura', 'nroFactura', 'informada', 'monto'], 'required'],
            [['fecha_factura', 'fecha_informada'], 'safe'],
            [['monto'], 'number'],
            [['id_tiket'], 'integer'],
            [['errores'], 'string'],
            [['nroFactura', 'cae', 'ptoVta'], 'string', 'max' => 255],
            [['informada'], 'string', 'max' => 1],
            [['id_tiket'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tiket::className(), 'targetAttribute' => ['id_tiket' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fecha_factura' => 'Fecha Factura',
            'nroFactura' => 'Nro Factura',
            'informada' => 'Informada',
            'fecha_informada' => 'Fecha Informada',
            'monto' => 'Monto',
            'cae' => 'Cae',
            'ptoVta' => 'Pto Vta',
            'id_tiket' => 'Id Tiket',
            'errores' => 'Errores',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTiket()
    {
        return $this->hasOne(\app\models\Tiket::className(), ['id' => 'id_tiket']);
    }




}
