<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "lote".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $fecha
 *
 * @property \app\models\RegistroLote[] $registroLotes
 * @property string $aliasModel
 */
abstract class Lote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lote';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'fecha'], 'required'],
            [['fecha'], 'safe'],
            [['nombre'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'fecha' => 'Fecha',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegistroLotes()
    {
        return $this->hasMany(\app\models\RegistroLote::className(), ['id_lote' => 'id']);
    }




}
