<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "registro_lote".
 *
 * @property integer $id
 * @property integer $id_lote
 * @property string $nombre_cliente
 * @property string $tipo_dni
 * @property string $dni
 * @property string $email
 * @property string $concepto
 * @property string $monto
 * @property string $error
 *
 * @property \app\models\Lote $lote
 * @property \app\models\Tiket[] $tikets
 * @property string $aliasModel
 */
abstract class RegistroLote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'registro_lote';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_lote'], 'required'],
            [['id_lote'], 'integer'],
            [['monto'], 'number'],
            [['nombre_cliente', 'tipo_dni', 'dni', 'email', 'concepto', 'error'], 'string', 'max' => 255],
            [['id_lote'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Lote::className(), 'targetAttribute' => ['id_lote' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_lote' => 'Id Lote',
            'nombre_cliente' => 'Nombre Cliente',
            'tipo_dni' => 'Tipo Dni',
            'dni' => 'Dni',
            'email' => 'Email',
            'concepto' => 'Concepto',
            'monto' => 'Monto',
            'error' => 'Error',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLote()
    {
        return $this->hasOne(\app\models\Lote::className(), ['id' => 'id_lote']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTikets()
    {
        return $this->hasMany(\app\models\Tiket::className(), ['id_registro' => 'id']);
    }




}
