<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tiket".
 *
 * @property integer $id
 * @property string $nro_tiket
 * @property string $fecha_tiket
 * @property string $importe
 * @property string $fecha_pago
 * @property string $detalles
 * @property integer $id_registro
 *
 * @property \app\models\Factura[] $facturas
 * @property \app\models\RegistroLote $registro
 * @property string $aliasModel
 */
abstract class Tiket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tiket';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha_tiket', 'importe', 'fecha_pago', 'id_registro'], 'required'],
            [['fecha_tiket', 'fecha_pago'], 'safe'],
            [['importe'], 'number'],
            [['id_registro'], 'integer'],
            [['nro_tiket'], 'string', 'max' => 50],
            [['detalles'], 'string', 'max' => 255],
            [['id_registro'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\RegistroLote::className(), 'targetAttribute' => ['id_registro' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nro_tiket' => 'Nro Tiket',
            'fecha_tiket' => 'Fecha Tiket',
            'importe' => 'Importe',
            'fecha_pago' => 'Fecha Pago',
            'detalles' => 'Detalles',
            'id_registro' => 'Id Registro',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacturas()
    {
        return $this->hasMany(\app\models\Factura::className(), ['id_tiket' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegistro()
    {
        return $this->hasOne(\app\models\RegistroLote::className(), ['id' => 'id_registro']);
    }




}
